# Generated by Django 2.1.2 on 2018-11-21 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolled',
            name='post',
        ),
        migrations.RemoveField(
            model_name='enrolled',
            name='user',
        ),
        migrations.DeleteModel(
            name='Enrolled',
        ),
    ]
